### ISSUE TITLE
Allow opening playgrounds from GitHub repos

### ISSUE THREAD

**Issue by lostintangent** [codespaces-contrib/gistpad#116]
Currently, GistPad operates entirely on Gists as its backing storage. However, more complex playgrounds may benefit from being stored in a repo, since that would allow them to use directories, create PRs, etc. As a result, we should explore extending the “Open Gist” command to accept GitHub repo URLs, in addition to Gist URLs.

**Comment by RandomFractals** [comment]
+1 on this since the 2 data tools I created for charts and maps already do some of it by getting configs from github repos or gists.

Having gistpad support that dev workflow would simplify things for custom gistpad viewers intergrations ...

**Comment by lostintangent** [comment]
This is now enabled via the new [CodeSwing extension](https://aka.ms/codeswing) 👍
