### ISSUE TITLE
Enable debugging for playgrounds

### ISSUE THREAD

**Issue by cognominal** [codespaces-contrib/gistpad#123]
I am not familiar enough enough with javascript and vscode to be more specific but here what I
get when I type F5. See screenshot. I will try to disable the other gist extension and I will keep you posted.

<img width="657" alt="Capture d’écran 2020-02-14 à 19 17 25" src="https://user-images.githubusercontent.com/16176/74557005-88925400-4f5f-11ea-8f65-ce22655d8c2f.png">

Otherwise gistpad seems very promising.

**Comment by lostintangent** [comment]
@cognominal Hey! Could you explain what you were trying to do? Did you create a playground and want to debug the JavaScript? This isn't currently enabled, but it's something I could look into 👍

**Comment by cognominally** [comment]
That is probably what I did. Anyway gistpad seems on the right track.
May be you should be clear in the doc about the current limitations to lessen unrealistic expectations.
I hope down in the road I will be capable to give a better feedback.
Keep the good work.

**Comment by lostintangent** [comment]
@cognominal I wouldn’t call this an unrealistic expectation. I just haven’t enabled debugging yet. It’s totally possible, so I’ll use this work item to track the status of this work 👍

**Comment by lostintangent** [comment]
Closing this in favor of CodeSwing
