### ISSUE TITLE
Layout that doesn't require the preview pane shown

### ISSUE THREAD

**Issue by Confirm4Crit** [codespaces-contrib/gistpad#174]
**Is your feature request related to a problem? Please describe.**
Taking JS classes right now, I don't need the front end at all, just a `console.log.`

**Describe the solution you'd like**
A way to close or hide the preview pane without dismissing the whole playground.

**Describe alternatives you've considered**
Living with it and making it tiny. 😄

**Comment by lostintangent** [comment]
Closing this in favor of the new [CodeSwing](https://aka.ms/codeswing), where I'll be implementing this in 👍
