### ISSUE TITLE
Support for snowpack

### ISSUE THREAD

**Issue by allforabit** [codespaces-contrib/gistpad#177]
**Is your feature request related to a problem? Please describe.**
I'd like to use some more exotic packages and currently there's a limited set of packages available through cdnjs. I know you can paste in urls from the likes of jsdelivr and unkpkg but I'm just not sure how to use some packages like this. I think they have to be designed with these services in mind.

**Describe the solution you'd like**
A solution could be to use snowpack which is developed for "Unbundled Development" which is something that gistpad seems to be designed for.

**Describe alternatives you've considered**
I've tried jsdeliver and unpkg as a possible workaround.

In general really love the approach of Gistpad, it's an amazing and ambitious extension!

**Comment by lostintangent** [comment]
Hey! This is similar to #99, and I agree that having better Snowpack support would be great! Let me take a look at how this might work 👍

**Comment by lostintangent** [comment]
Hey! I factored the playground capability out of GistPad and into a new extension called [CodeSwing](https://aka.ms/codeswing). I migrated this issue to the [CodeSwing repo](https://github.com/codespaces-contrib/codeswing/issues/6), and I'll be tracking it there moving forward 👍

**Comment by allforabit** [comment]
OK thanks, going to give the new extension a go now :-)

**Comment by lostintangent** [comment]
I'm likely going to be working on the Skypack experience in the next few days, and so stay tuned on that. In the meantime, please ping me with any issues/feedback you have on the new CodeSwing repo. I'm super keen for feedback! 😎
