### ISSUE TITLE
Need ability to diff the gist changes before committing them.

### ISSUE THREAD

**Issue by mithunshanbhag** [codespaces-contrib/gistpad#196]
**Is your feature request related to a problem? Please describe.**
Currently when editing gists via gistpad, I cannot diff the changes before committing them.

**Describe the solution you'd like**
Would be great if somehow `source control` tab (highlighted below) would also show the proposed changes to gists.   

![image](https://user-images.githubusercontent.com/2327905/100488143-6eaeb000-3132-11eb-9d11-c3794662b809.png)

**Describe alternatives you've considered**
AFAIK, currently there is no way to diff any proposed gist changes prior to committing them.

**Additional context**
None.

**Comment by lostintangent** [comment]
Hey! If you want this level of control over your gists, would it make sense to just clone them locally and make commits manually? If you right-click a gist, there's an option to clone it. I added that as a fallback for situations where folks needed more flexibility than GistPad could provide 👍

The commit-on-save behavior is one of the core reasons I built GistPad, so I'd love to discuss alternatives to adding a commit step. I'm still planning to expose revision history into the extension, at which point, I'd prefer to leave the commit-on-save as-is, and simply make it easier to view diffs and then revert then if necessary.

**Comment by lostintangent** [comment]
Now that the playground feature has moved into the [CodeSwing](https://aka.ms/codeswing) extension, which allows you to create swings/playgrounds via local files or GitHub repos, you have a lot more control over committing changes. Therefore, I'm going to close this as resolved, but please let me know if CodeSwing doesn't address your request. Thanks!
