### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by methyl** [codespaces-contrib/gistpad#200]
When trying to Sign In to Github, after completing the authentication flow nothing happens.

**To Reproduce**
1. Click Sign In
2. Authorize application
3. Open VSCode
4. Log says the log in was successful, but extension doesn't recognize it.
**Screenshots**
![image](https://user-images.githubusercontent.com/692367/103160096-4669ae00-47d1-11eb-921c-7b8d0e5e34a9.png)

**Desktop (please complete the following information):**
```
GistPad Version [e.g. v0.2.0]
VSCode Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.11-3-MANJARO
```

**Comment by lostintangent** [comment]
Thanks for reporting this, and apologies for the issue. If you reload VS Code, does the GistPad tree populate? I just tried reproing this on my mac and I couldn't, and so I'm just wondering if there's an issue with the initial tree refresh on Linux? Let me try to test this in a Linux environment.

**Comment by methyl** [comment]
Restarting does not help, it only allows me to sign in again (after the first sign in, the button stops to react until vscode is restarted)

**Comment by methyl** [comment]
There are some errors visible in dev tools after trying to sign in:
![image](https://user-images.githubusercontent.com/692367/103170433-7a31eb80-4844-11eb-99c3-0084120c59cb.png)

**Comment by lostintangent** [comment]
Hmm, OK. I'll try to see if I can reproduce this issue. Also, just to confirm: do you know if you have libsecret and gnome-letting installed on your machine? I believe those are both required in order for VS Code to securely store the auth secrets.

**Comment by methyl** [comment]
So it seems my keyring was busted. I removed the one I had via `seahorse` (according to this guide https://wiki.archlinux.org/index.php/GNOME/Keyring#Passwords_are_not_remembered) and after restarting VSCode Sign In is working! Thanks for help.

**Comment by lostintangent** [comment]
Awesome! I'm glad to hear you're unblocked 😁
