### ISSUE TITLE
Command 'gistpad.exportGistToCodePen' not found

### ISSUE THREAD

**Issue by methyl** [codespaces-contrib/gistpad#202]
**Describe the bug**
When running "Export to Codepen", this error shows up:
```
Error running command gistpad.exportGistToCodePen: command 'gistpad.exportGistToCodePen' not found. This is likely caused by the extension that contributes gistpad.exportGistToCodePen.
```

**To Reproduce**
1. Create a CodeSwing via GistPad
2. Go to GistPad tab
3. Right-click on the gist and select Export to CodePen

**Expected behavior**
CodePen is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/692367/103215226-0f031a80-4913-11eb-8224-30ad0072d610.png)

**Desktop (please complete the following information):**
```
GistPad 0.2.0
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.11-3-MANJARO
```

**Comment by lostintangent** [comment]
Hey! I broke this as part of the CodeSwing refactoring and I've got a fix for it, that I'll deploy this afternoon. Apologies for the inconvenience!

**Comment by lostintangent** [comment]
The fix for this has now been shipped!
