### ISSUE TITLE
Publish this extension to https://open-vsx.org

### ISSUE THREAD

**Issue by jmeischner** [codespaces-contrib/gistpad#204]
**Is your feature request related to a problem? Please describe.**
I'm using VSCodium and want to install this extension via *Extensions* from inside VSCodium

**Describe the solution you'd like**
VSCodium uses the extension index form [open-vsx.org](https://open-vsx.org) as described in their [docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace). It would be great, if I can just installed it from inside VSCodium and it works.

**Describe alternatives you've considered**
Installing *.vsix* directly. Unfortunately the Github login process from within the extension is then somehow not working 🤷‍♂️

**Comment by lostintangent** [comment]
Hey! Thanks for reaching out. Unfortunately, I don't have the time to maintain support for other VS Code distributions/marketplaces, and as you discovered, I'm assuming there are issues with auth/etc. there. For now, I don't want to set the wrong expectations by pushing to to OpenVSX, and so I'm going to close this, and will revisit it in the future based on user demand 👍
