### ISSUE TITLE
Ability to move gist from secret to public and vice versa

### ISSUE THREAD

**Issue by osadasami** [codespaces-contrib/gistpad#208]
It would be great if we can right click on gist and select something like `Make public` if current gist is secret, and `Make secret` if current gist is private

**Comment by lostintangent** [comment]
Hey! This feature request definitely makes sense. Unfortunately, the current Gist API doesn't allow changing the visibility of a gist, so in order for me to support this, I'd need to create a new gist and then delete the previous one. Would that be OK? That would have the side-effect of changing the ID/URL of the gist, and I believe that any comments would also be lost. But we'd be able to retain the file contents and commit history.

**Comment by osadasami** [comment]
I checked Github gist functionality and notice that we can move gist from secret to public but not the opposite. So I close that issue because it's impossible to create that functionality with current Github API. @lostintangent thanks for your feedback. I think with GistPad it's easy to create new gist and copy content from old gist.

**Comment by reidcooper** [comment]
I'd be interested in a default setting that uploads the Gist Public or Private. I can always worry about it later via Github's site. I like to default everything to private and then decide later if something should be public. I'm conservative on what I share publicly.
