### ISSUE TITLE
Re-open playground preview after restarting VS Code

### ISSUE THREAD

**Issue by lostintangent** [codespaces-contrib/gistpad#59]
Currently, if you have a playground open and then restart VS Code, the playground files (e.g. index.html) and WebView remain open, but the preview window isn’t properly hooked up. As a result, the user has to re-open the playground in order to start working on it again.

To make this experience smoother, we should detect the restart and then re-initialize the playground automatically.

**Comment by RandomFractals** [comment]
I believe the same happens for open gists as workspace scenario when you restart vscode, i.e. open gist files restore is not implement yet? I that what you mean by playground?

**Comment by lostintangent** [comment]
Closing in favor of CodeSwing
